### ISSUE TITLE
Error Connecting to Sensor

### ISSUE THREAD

**Issue by FernandezR** [ros-drivers/um7#10]
We are trying to connect to a UM7 sensor with your package, but we get the following output

[ INFO] [1475608698.166198336]: um7_driver ver 0.0.2 connected to serial port.
[ WARN] [1475608698.264480968]: Timed out waiting for packet from device.
[ WARN] [1475608698.362741924]: Timed out waiting for packet from device.
[ WARN] [1475608698.460995196]: Timed out waiting for packet from device.
[ WARN] [1475608698.559263214]: Timed out waiting for packet from device.
[ WARN] [1475608698.657529558]: Timed out waiting for packet from device.
[ERROR] [1475608698.657928239]: Unable to set CREG_COM_SETTINGS.

Is this an issue with our device or the package?

Thanks

**Comment by zastrix** [comment]
Looks like your configuration needs some attention. try changing the COM port settings.

**Comment by FernandezR** [comment]
The device is just connected as dev/ttyUSB0. What settings am I supposed to change? It's our understanding that the device should just work plug and play, as it comes configured from the manufacturer.

**Comment by zastrix** [comment]
I couldn't tell you without further information. This however doesn't seem to be a package related issue, rather a configuration issue. Try a post on Ros Answers (http://answeres.ros.org) with your detailed configuration.

**Comment by tonybaltovski** [comment]
Did you change any of the default parameters?  This seems like a serial communication issue.  Have you tested it with the software CH provides?
