### ISSUE TITLE
um7_driver was unable to connect to port /dev/ttyUSB0

### ISSUE THREAD

**Issue by MinMengbin** [ros-drivers/um7#14]
Hi there. 

How is your project with UM7 going? 

I received the UM 7 and did a quick test on Windows. All were good for Windows. But I would use this UM 7 (http://www.chrobotics.com/shop/um7-orientation-sensor) on Linux system for my project and I installed the ROS node (http://wiki.ros.org/um7) of UM7. I got an error, um7_driver was unable to connect to port /dev/ttyUSB0 (shown as the picture) , when I tried to connect with sensor. I tried dmesg | grep tty, it was clearly shown that FTDI USB Serial Device Converter now attached to ttyUSB0.

The system is 64-bit Ubuntu 16.04LTS, the version of ROS is kinetic. 

Do you know what is wrong with that? 

By the way, should I use usb 2.0 not usb 3.0?

Thanks for your help.

Mike
![error_rosnode_um7](https://user-images.githubusercontent.com/9654214/28802544-16d2c92e-76ab-11e7-846f-e6a50fa94a19.png)

**Comment by MinMengbin** [comment]
Today, I tried the latest FTDI Linux driver. The version is 1.4.6 (http://www.ftdichip.com/Drivers/D2XX.htm). After downloading, I unzipped the file under the directory of Downloads. The folder is called release. Locate the release folder, and open the folder, then click the file ReadMe.txt. Follow the step and install the D2XX library. 
Note: If you see the error of **main.c:22:20: fatal error: ftd2xx.h: No such file or directory
compilation terminated.**, just find the folder /release/examples/loopback, open the main.c file under the folder of loopback, then change #include "ftd2xx.h" to  #include "../ftd2xx.h". Because ftd2xx.h is under the parent folder called examples. 

One thing I want to emphases that I got a FT_Open error, so I removed the default driver followed by the instructions. Shown below.
![ft_open remove](https://user-images.githubusercontent.com/9654214/28857184-8fcedaa2-779b-11e7-887b-72ba87023776.png)

After that, I can communicate with UM7 by this new library example. 
![connect_libary](https://user-images.githubusercontent.com/9654214/28857344-055d3c54-779d-11e7-8434-726872e30ccc.png)


But it did not work for rosrun um7 um7_driver _port:=/dev/ttyUSB0. 
While, I reckon it is the problem of the driver needed to be updated.

**Comment by MinMengbin** [comment]
I also tried this below today, but still did not work. I think I am getting there.

roscore
(New terminal)

sudo rmmod ftdi_sio 
sudo rmmod usbserial
rosrun um7 um7_driver _port:= /dev/ttyS0

(Error)
[ INFO] [1501654046.778168780]: um7_driver successfully connected to serial port /dev/ttyS0.
[ WARN] [1501654046.876552364]: Timed out waiting for packet from device.
[ WARN] [1501654046.975073620]: Timed out waiting for packet from device.
[ WARN] [1501654047.073503167]: Timed out waiting for packet from device.
[ WARN] [1501654047.171941928]: Timed out waiting for packet from device.
[ WARN] [1501654047.270367141]: Timed out waiting for packet from device.
[ERROR] [1501654047.270619649]: Unable to set CREG_COM_SETTINGS.
[ INFO] [1501654047.270675434]: Attempting reconnection after error.
[ INFO] [1501654048.271094300]: um7_driver successfully connected to serial port /dev/ttyS0.
[ WARN] [1501654048.369515888]: Timed out waiting for packet from device.
[ WARN] [1501654048.467940860]: Timed out waiting for packet from device.
[ WARN] [1501654048.566373590]: Timed out waiting for packet from device.
[ WARN] [1501654048.664794739]: Timed out waiting for packet from device.
[ WARN] [1501654048.763208896]: Timed out waiting for packet from device.
[ERROR] [1501654048.763393238]: Unable to set CREG_COM_SETTINGS.
[ INFO] [1501654048.763439051]: Attempting reconnection after error.

**Comment by trainman419** [comment]
The FTDI drivers that come default with the linux kernel have NEVER given me trouble. Since the device is detecting correctly, you almost certainly do not need to update the driver.

Fruther, unloading the `usbserial` and `ftdi_sio` drivers will cause the device  ( `/dev/ttyUSB0` ) to go away, so that's probably not helping.

Almost all USB serial issues that users have are not having the correct permissions to access the device. You should:

 * Look at the device permissions with `ls -l /dev/ttyUSB0` . This will probably look something like `crw-rw---- 1 root dialout 4, 64 Jul 26 09:23 /dev/ttyUSB0`
 * In this case, `root` is the user that owns the device, and `dialout` is the group.
 * Run the `groups` command to list the groups that your user is a member of, and confirm that the device group is there.
 * If you aren't in the device group, run `sudo usermod -a -G dialout $USER` to add yourself, and then log out and log back in (or reboot) to get the new group membership on your session.

**Comment by MinMengbin** [comment]
Hi, Trainman:
Thanks for your so detailed reply. Your answer solves the problem. 

Regards
Mike

**Comment by robodhruv** [comment]
Hi!

I am facing this same issue and @trainman419's resolution did not help me.

I can confirm that just like @MinMengbin, I am able to communicate with the UM7 if I install the new FTD2xx library and `sudo rmmod ftdi_sio` on my computer. I'm still unable to run `rosrun um7 um7_driver`. Any leads appreciated!
