### ISSUE TITLE
Timed out,  Received packet without data, Discarding packet due to bad checksum and flushing serial read buffer

### ISSUE THREAD

**Issue by MinMengbin** [ros-drivers/um7#15]
Hi, do you have some [warn]s like these?

 rosrun um7 um7_driver _port:=/dev/ttyUSB0 _update_rate:=50

[ INFO] [1501732773.702682748]: um7_driver successfully connected to serial port /dev/ttyUSB0.
[ WARN] [1501732773.819597255]: Timed out waiting for packet from device.
[ WARN] [1501732773.863397482]: Discarded 41 junk byte(s) preceeding packet.
[ WARN] [1501732773.863494561]: Serial read buffer is 431, now flushing in an attempt to catch up.
[ INFO] [1501732773.891295908]: Received packet 02 without data.
[ INFO] [1501732773.894725126]: Setting update rate to 50Hz
[ INFO] [1501732773.914213060]: Received packet 02 without data.
[ INFO] [1501732773.938239142]: Received packet 04 without data.
[ INFO] [1501732773.977235337]: Received packet 05 without data.
[ WARN] [1501732774.026532381]: Timed out waiting for packet from device.
[ WARN] [1501732774.069536633]: Discarded 45 junk byte(s) preceeding packet.
[ WARN] [1501732774.069628127]: Serial read buffer is 396, now flushing in an attempt to catch up.
[ WARN] [1501732774.092074544]: Discarded 19 junk byte(s) preceeding packet.
[ WARN] [1501732774.143063762]: Discarding packet due to bad checksum.
[ WARN] [1501732774.143169003]: Serial read buffer is 282, now flushing in an attempt to catch up.
[ INFO] [1501732774.174029741]: Received packet 06 without data.
[ INFO] [1501732774.206906784]: Received packet 08 without data.
[ INFO] [1501732774.208809340]: Sending command: zero gyroscopes
[ INFO] [1501732774.239888072]: Received packet ad without data.
[ WARN] [1501732774.458634799]: Discarding packet due to bad checksum.
[ WARN] [1501732774.458720103]: Serial read buffer is 366, now flushing in an attempt to catch up.
[ WARN] [1501732774.507630609]: Discarded 44 junk byte(s) preceeding packet.
[ WARN] [1501732774.590475107]: Serial read buffer is 445, now flushing in an attempt to catch up.
[ WARN] [1501732774.665381406]: Discarded 16 junk byte(s) preceeding packet.
[ WARN] [1501732774.665467692]: Serial read buffer is 350, now flushing in an attempt to catch up.
[ WARN] [1501732774.783228301]: Discarding packet due to bad checksum.

Thanks, Mike

**Comment by faye-panasonic** [comment]
hi! did you every solve this?

**Comment by zastrix** [comment]
If I had to guess, it looks like the some serial port settings are incorrect. Take a look and see if you have these set (where ttyUSB0 is your USB port):
```
<param name="port" value="/dev/ttyUSB0" />
<param name="baud" value="115200" />
```
Also verify you are using the correct logic voltage level FTDI serial chip (i believe it is 3.3V). Please let me know if any of this helps.

**Comment by alan707** [comment]
I am getting the following error:
```sh
[ERROR] [1515801507.416581059]: Unable to set CREG_COM_SETTINGS.
[ INFO] [1515801507.416640135]: Attempting reconnection after error.
[ INFO] [1515801508.417024559]: um7_driver successfully connected to serial port /dev/ttyUSB0.
[ INFO] [1515801508.419538140]: Received packet 02 without data.
[ WARN] [1515801508.468800744]: Timed out waiting for packet from device.
[ INFO] [1515801508.471698586]: Received packet 02 without data.
[ WARN] [1515801508.520969626]: Timed out waiting for packet from device.
[ INFO] [1515801508.523395174]: Received packet 02 without data.
[ WARN] [1515801508.572677586]: Timed out waiting for packet from device.
[ERROR] [1515801508.585460717]: SerialException device reports readiness to read but returned no data (device disconnected?) failed.
[ INFO] [1515801508.585565234]: Attempting reconnection after error.
[ INFO] [1515801509.586022288]: um7_driver successfully connected to serial port /dev/ttyUSB0.
[ INFO] [1515801509.588597614]: Received packet 02 without data.
[ WARN] [1515801509.637881882]: Timed out waiting for packet from device.
[ERROR] [1515801509.752211345]: SerialException device reports readiness to read but returned no data (device disconnected?) failed.
```

**Comment by tonybaltovski** [comment]
What Linux kernel are you using? There was a change at started causing these issues.

**Comment by MinMengbin** [comment]
Please do not use this product. It is not calibrated and poorly supported.
