### ISSUE TITLE
Possible memory leak

### ISSUE THREAD

**Issue by WbHappy** [ros-drivers/um7#27]
Hello everyone,

I am intensively using the um7 driver for some weeks now and I unfortunately noticed a possible memory leak...

![image](https://user-images.githubusercontent.com/11755284/91711387-19d8b900-eb86-11ea-9a32-8143765a1a3f.png)

Did anyone noticed this after running the driver for more than 24 hours ? I would gladly use any available help :).

Best,

**Comment by axelfar** [comment]
The problem come from ROS publishers initialization inside _publishMsgs_ method in main cpp file.

![image](https://user-images.githubusercontent.com/34505045/92087671-16cf0a00-edcc-11ea-84e6-d3a4d961f537.png)

They are called back on each loop iteration. They just need to be removed from this method and placed outside the while loop.

**Comment by WbHappy** [comment]
Thanks, tested and result is there ;).

Closing issue.
