### ISSUE TITLE
Noetic release

### ISSUE THREAD

**Issue by Tobias-Fischer** [ros-drivers/um7#28]
Hi there, could you please release this package for noetic?

Many thanks, Tobi

**Comment by tonybaltovski** [comment]
It is blocked on https://github.com/wjwwood/serial/issues/222

**Comment by gmetts** [comment]
Blocking issue with noetic serial seems to be cleared. Could this now be released for noetic?

Thanks,

Grant

**Comment by tonybaltovski** [comment]
Released: https://github.com/ros/rosdistro/pull/32761
