### ISSUE TITLE
Angular and linear velocity covariances cannot be set

### ISSUE THREAD

**Issue by skohlbr** [ros-drivers/um7#3]
The driver currently only supports setting the full orientation covariance matrix, but there apparently is no way to set the angular and linear velocity covariances. The UM6 driver in contrast allows for also setting those and setting them from parameters: https://github.com/ros-drivers/um6/blob/indigo-devel/src/main.cpp#L327

**Comment by rbirac** [comment]
Hi Stefan,

Both the UM6 and the UM7 have been discontinued.  Too bad as I rather liked them.  As such, I have no plans to maintain the UM7 driver.  I am also not a professional programmer and going through the official ROS process of releasing that driver was more than I want to do again.  If you are interested in supporting it, I could probably figure out how to transfer the project over to you.  Let me know if you are interested.   Or you can just download the source files and create your own modifications.  That sounds easiest to me.

Alex

From: Stefan Kohlbrecher 
Sent: Thursday, January 21, 2016 11:52 PM
To: ros-drivers/um7 
Subject: [um7] Angular and linear velocity covariances cannot be set (#3)

The driver currently only supports setting the full orientation covariance matrix, but there apparently is no way to set the angular and linear velocity covariances The UM6 driver in contrast allows for also setting those and setting them from parameters: https://githubcom/ros-drivers/um6/blob/indigo-devel/src/maincpp#L327

**Comment by skohlbr** [comment]
I wanted to finally get a grip on the whole ROS release procedure anyways, so I could take over. Will get back to you after next week (in which I'll work some more on UM7 hardware). Thanks for the quick reply.
