### ISSUE TITLE
Package maintenance

### ISSUE THREAD

**Issue by ibaranov-cp** [ros-drivers/um7#6]
Hello,

Is the official maintainer Alex Brown still maintaining this package?

Should it be handed over to Clearpath Robotics or other parties?

Thanks.

**Comment by jack-oquin** [comment]
A reasonable question, since the only commit activity was in February 2015, a little over a year ago now.

The only other open issue with this driver (#3), suggests that @rbirac is indeed looking for a new maintainer, and that @skohlbr is willing to take over.

**Comment by rbirac** [comment]
Hi Ilia,

```
For various reasons, I’m not working in ROS anymore.  Clearpath was not interested in supporting the UM7, hence I have transferred the package to Daniel Miller at dgmiller@ncsu.edu who offered to maintain it.
```

Alex

From: Ilia Baranov 
Sent: Monday, March 28, 2016 7:05 AM
To: ros-drivers/um7 
Subject: [um7] Package maintenance (#6)

Hello,

Is the official maintainer Alex Brown still maintaining this package?

Should it be handed back over to Clearpath Robotics?

Thanks.

**Comment by jack-oquin** [comment]
@rbirac: Thanks for arranging continuing maintenance.

**Comment by ibaranov-cp** [comment]
Hello,

I don't see Daniel as a maintainer and can't find him as a github user.

Mind pointing me in the right direction?

Thanks.

**Comment by rbirac** [comment]
Hi Ilia,
Daniel is on Github at http://www.github.com/zastrix and his email is dgmiller@ncsu.edu.

Alex

**Comment by tonybaltovski** [comment]
The Husky is migrating to the UM7 and I would be interested in helping maintaining this driver.
